name: Build & Publish app

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install
        run: |
          npm install
          npm install @angular/cli
          npm install firebase-tools
      - name: increase version
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch --force -m "Version %s"
          git push
          git push --tags
      - name: build prod version
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install
          npm install @angular/cli
          npm install firebase-tools

          npm run sw-build
          # ng build --prod
          firebase login --token "$FIREBASE_TOKEN"
          ng deploy
          
